#+TITLE: Mehmet Tekman
#+OPTIONS: toc:2

#+HTML: <table>
#+HTML: <tr><td>Contact</td><td>
#+HTML: <a href="https://gitter.im/mtekman">
#+HTML:   <img src="https://img.shields.io/badge/Gitter-mtekman-informational?style=flat&color=393&logoColor=white&logo=gitter" />
#+HTML: </a>
#+HTML: <a href="mailto:mtekman89@gmail.com">
#+HTML:   <img src="https://img.shields.io/badge/-mtekman89-informational?style=flat&color=393&logoColor=white&logo=gmail&labelColor=grey" />
#+HTML: </a>
#+HTML: </td></tr>
#+HTML: <tr><td>CV + Academia</td><td>
#+HTML: <a href="https://orcid.org/0000-0002-4181-2676">
#+HTML:   <img src="https://img.shields.io/badge/ORCID-0000--0002--4181--2676-informational?style=flat&color=393&logoColor=white&logo=orcid" />
#+HTML: </a>
#+HTML: <a href="https://www.researchgate.net/profile/Mehmet_Tekman">
#+HTML:   <img src="https://img.shields.io/badge/-ResearchGate-informational?style=flat&color=393&logoColor=white&logo=researchgate&labelColor=grey" />
#+HTML: </a>
#+HTML: <a href="https://scholar.google.de/citations?user=HVwU31YAAAAJ">
#+HTML:   <img src="https://img.shields.io/badge/-GScholar-informational?style=flat&color=393&logoColor=white&logo=google-scholar&labelColor=grey" />
#+HTML: </a>
#+HTML: <a href="CV/mtekman_cv.2020.pdf">
#+HTML:   <img src="https://img.shields.io/badge/CV-Resume-informational?style=flat&color=d66&logoColor=white&logo=internet-archive&labelColor=grey" />
#+HTML: </a>
#+HTML: </td></tr>
#+HTML: </table>





Hey. This is a little static profile. It's by far not everything, but I've included repos of mine that I either dedicated a lot of time to, or am proud in some teeny tiny way. Click the badges above for links to my public profiles.


/In Brief:/

#+HTML: <a href="" >
#+HTML:   <img src="https://img.shields.io/badge/Linux-NixOS+Arch-informational?style=flat&logo=linux&labelColor=444&logoColor=white&color=b44baa" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:   <img src="https://img.shields.io/badge/Editor-Emacs-informational?style=flat&labelColor=444&logo=gnu-emacs&logoColor=red&color=b44baa" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:   <img src="https://img.shields.io/badge/Life-Org--Mode-informational?style=flat&labelColor=444&logo=gnu&logoColor=&color=b44baa" />
#+HTML: </a></td></tr>

-----

/In Essence:/

#+HTML: <table>
#+HTML: <thead><tr>
#+HTML:   <th>Languages + Frameworks</th>
#+HTML:   <th>Daily Drivers</th>
# #+HTML:   <th>Things I respect</th>
#+HTML: </tr></thead>
#+HTML: <tbody><tr><td>
/Languages/
#+HTML: <a href="" >
#+HTML:     <img src="https://img.shields.io/badge/-Bash-informational?style=flat&color=blue&logoColor=white&labelColor=black&logo=gnu-bash" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:     <img src="https://img.shields.io/badge/-R-informational?style=flat&color=blue&logoColor=white&labelColor=black&logo=r" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:     <img src="https://img.shields.io/badge/-Python-informational?style=flat&color=blue&logoColor=white&labelColor=black&logo=python" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:     <img src="https://img.shields.io/badge/-Javascript-informational?style=flat&color=blue&logoColor=white&labelColor=black&logo=javascript" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:     <img src="https://img.shields.io/badge/-C/C++-informational?style=flat&color=blue&logoColor=white&labelColor=black&logo=C" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:     <img src="https://img.shields.io/badge/-Perl-informational?style=flat&color=blue&logoColor=white&labelColor=black&logo=perl" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:     <img src="https://img.shields.io/badge/-MariaDB/SQLite-informational?style=flat&color=blue&logoColor=white&labelColor=black&logo=mariadb" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:     <img src="https://img.shields.io/badge/-PHP-informational?style=flat&color=blue&logoColor=white&labelColor=black&logo=php" />
#+HTML: </a>
#+HTML: <a href="" >
#+HTML:     <img src="https://img.shields.io/badge/Lisp-Emacs+Common-informational?style=flat&color=blue&logoColor=white&labelColor=black" />
#+HTML: </a>
/Frameworks/
#+HTML: <a href="https://magit.vc/">
#+HTML:   <img src="https://img.shields.io/badge/-Git+Magit-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=git" />
#+HTML: </a>
#+HTML: <a href="https://orgmode.org/">
#+HTML:   <img src="https://img.shields.io/badge/-Org--Mode-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=gnu-emacs" />
#+HTML: </a>
#+HTML: <a href="https://jupyter.org/">
#+HTML:   <img src="https://img.shields.io/badge/-Jupyter-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=jupyter" />
#+HTML: </a>
#+HTML: <a href="https://pandas.pydata.org/">
#+HTML:   <img src="https://img.shields.io/badge/-Pandas-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=pandas" />
#+HTML: </a>
#+HTML: <a href="https://dplyr.tidyverse.org/">
#+HTML:   <img src="https://img.shields.io/badge/R-dplyr+ggplot2-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=" />
#+HTML: </a>
# #+HTML: <a href="https://bioconda.github.io/">
# #+HTML:   <img src="https://img.shields.io/badge/-bioconda-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=anaconda" />
# #+HTML: </a>
#+HTML: <a href="https://www.qt.io/">
#+HTML:   <img src="https://img.shields.io/badge/-Qt-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=qt" />
#+HTML: </a>
#+HTML: <a href="https://cmake.org/">
#+HTML:   <img src="https://img.shields.io/badge/-Make/CMake-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=cmake" />
#+HTML: </a>
#+HTML: <a href="https://github.com/conda/conda">
#+HTML:   <img src="https://img.shields.io/badge/-Conda-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=anaconda" />
#+HTML: </a>
#+HTML: <a href="https://www.docker.com/">
#+HTML:   <img src="https://img.shields.io/badge/-Docker-informational?style=flat&color=brown&logoColor=white&labelColor=black&logo=docker" />
#+HTML: </a>
#+HTML: </td>
#+HTML: <td>
/Android/
#+HTML: <a href="https://lineageos.org/">
#+HTML:   <img src="https://img.shields.io/badge/-Lineage-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=lineageOS" />
#+HTML: </a>
#+HTML: <a href="https://f-droid.org/">
#+HTML:   <img src="https://img.shields.io/badge/-F--Droid-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=f-droid" />
#+HTML: </a>
#+HTML: <a href="https://magisk.me/">
#+HTML:   <img src="https://img.shields.io/badge/-magisk-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=magisk" />
#+HTML: </a>
/Desktop/
#+HTML: <a href="https://stumpwm.github.io/">
#+HTML:   <img src="https://img.shields.io/badge/WM-StumpWM-informational?style=flat&color=purple&logoColor=white&labelColor=black" />
#+HTML: </a>
#+HTML: <a href="https://www.gnu.org/software/gnuzilla/">
#+HTML:   <img src="https://img.shields.io/badge/-IceCat-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=gnu-icecat" />
#+HTML: </a>
#+HTML: <a href="https://www.mozilla.org/en-US/">
#+HTML:   <img src="https://img.shields.io/badge/-Firefox-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=firefox" />
#+HTML: </a>
#+HTML: <a href="https://www.blender.org/">
#+HTML:   <img src="https://img.shields.io/badge/-Blender-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=blender" />
#+HTML: </a>

# #+HTML: <a href="https://www.audacityteam.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-Audacity-informational?style=flat&color=&logoColor=white&labelColor=black&logo=audacity" />
# #+HTML: </a>

#+HTML: <a href="https://www.gimp.org/">
#+HTML:   <img src="https://img.shields.io/badge/-GIMP-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=gimp" />
#+HTML: </a>
#+HTML: <a href="https://inkscape.org/">
#+HTML:   <img src="https://img.shields.io/badge/-Inkscape-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=inkscape" />
#+HTML: </a>
#+HTML: <a href="https://ublockorigin.com/">
#+HTML:   <img src="https://img.shields.io/badge/-uBlockO-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=ublock-origin" />
#+HTML: </a>
#+HTML: </td>
# #+HTML: <td>
# #+HTML: <a href="https://bioconda.github.io/">
# #+HTML:   <img src="https://img.shields.io/badge/-bioconda-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=anaconda" />
# #+HTML: </a>
# #+HTML: <a href="https://conda-forge.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-conda--forge-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=conda-forge" />
# #+HTML: </a>
# #+HTML: <a href="https://www.gnu.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-GNU+FSF-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=gnu" />
# #+HTML: </a>
# #+HTML: <a href="https://www.mozilla.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-Mozilla-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=mozilla" />
# #+HTML: </a>
# #+HTML: <a href="https://mastodon.social/">
# #+HTML:   <img src="https://img.shields.io/badge/-Mastodon-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=mastodon" />
# #+HTML: </a>
# #+HTML: <a href="https://melpa.org/#/">
# #+HTML:   <img src="https://img.shields.io/badge/-MELPA-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=gnu-emacs" />
# #+HTML: </a>
# #+HTML: <a href="https://www.openstreetmap.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-OpenStreetMap-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=openstreetmap" />
# #+HTML: </a>
# #+HTML: <a href="https://ipfs.io/">
# #+HTML:   <img src="https://img.shields.io/badge/-IPFS-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=ipfs" />
# #+HTML: </a>
# #+HTML: <a href="https://kodi.tv/">
# #+HTML:   <img src="https://img.shields.io/badge/-Kodi-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=kodi" />
# #+HTML: </a>
# #+HTML: <a href="https://xfce.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-XFCE-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=xfce" />
# #+HTML: </a>
# #+HTML: <a href="http://www.gnome.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-Gnome-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=gnome" />
# #+HTML: </a>
# #+HTML: <a href="https://www.archlinux.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-Arch-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=arch-linux" />
# #+HTML: </a>
# #+HTML: <a href="https://nixos.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-NixOS-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=nixos" />
# #+HTML: </a>
# #+HTML: <a href="https://www.gentoo.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-gentoo-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=gentoo" />
# #+HTML: </a>
# #+HTML: <a href="https://forum.xda-developers.com/android/">
# #+HTML:   <img src="https://img.shields.io/badge/-XDA-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=xda-developers" />
# #+HTML: </a>
# #+HTML: <a href="https://maemo.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-maemo-informational?style=flat&color=purple&logoColor=white&labelColor=black" />
# #+HTML: </a>
# #+HTML: <a href="https://www.wikipedia.org/">
# #+HTML:   <img src="https://img.shields.io/badge/-Wikipedia-informational?style=flat&color=purple&logoColor=white&labelColor=black&logo=wikipedia" />
# #+HTML: </a>
#+HTML: </td></tr></tbody></table>

-----

/In Detail:/

**** Work

***** Enterprise Software
****** Galaxy
+ [[https://github.com/galaxyproject/tools-iuc/pulls?q=is%3Apr+author%3Amtekman][tools-iuc]] - The tool recipe repository: 58 closed and 6 open pull-requests
+ [[https://github.com/galaxyproject/galaxy/pulls?q=is%3Apr+author%3Amtekman][galaxy]] - The core dev repository: 5 closed and 1 open pull-request
+ [[https://github.com/galaxyproject/training-material/pulls?q=is%3Apr+author%3Amtekman][training-material]] - The teaching materials repository: 37 closed pull-requests


***** Analysis
****** Linkage and Haplotype Analysis
+ [[https://github.com/mtekman/HaploForge][HaploForge]] - A Comprehensive Pedigree Drawing and Haplotype Visualisation Web Application.
+ [[https://github.com/mtekman/linkage_pipeline][Linkage Pipeline]] - Linkage Analysis pipeline for both Autosomal and X-linked penetrances.
+ [[https://github.com/mtekman/poster-haploforge][poster-haploforge]] - Latex poster for Haploforge
+ [[https://github.com/mtekman/phd_thesis][phd-thesis]] - Latex of PhD Thesis

****** Variant or Sequence Analysis
+ [[https://bitbucket.org/momo13/ovas-pipeline/][OVAS]] and [[https://github.com/mtekman/OVAS-ISOmaker][OVAS-maker]] - Open-source Variant Analysis Suite, and ISO maker.
+ [[https://github.com/mtekman/ngs_sequencing_pipeline][ngs-pipeline.sh]] - Skeleton for NGS pipeline, now backbone of OVAS project.
+ [[https://github.com/mtekman/bedtarget][bedtarget]] - Grabs regions of genetic context from UCSC databases and reformats them as BED files.
+ [[https://github.com/mtekman/genepender][genepender]] - Annotates (often overlapping) BED-defined regions to variants in a VCF file. Used for providing a gene/exon context to variants.
+ [[https://github.com/mtekman/funcannot][funcannot]] - Annotates cDNA, protein, mutation type, and other funcational changes to variants in a genepender'd VCF file

****** Genome-wide Association Studies
+  [[https://github.com/mtekman/MembranousScripts][MembranousScripts]] - Set of utilities used to perform basic allele testing and parallel processing of LocusZoom plots

***** Other
****** C++ based
+ [[https://github.com/mtekman/motiondetect][motiondetect]] - An FCam-based CImg motion-detector for Maemo devices. MSci Thesis.
+ [[https://github.com/mtekman/PreciseChisq][PreciseChisq]] - An example curses program tied in with PAM authentication that executes upon (maxtry) failure
****** Bioinformatic
+ [[https://github.com/mtekman/bamcover][bamcover]] - Performs basic pileup statistics of BAM files, depth and coverage.
+ [[https://github.com/mtekman/RefGeneStats][RefGeneStats]] - Human Genome Exon/Intron statistics from refGene
+ [[https://github.com/mtekman/comparing_matrices_mine_grun][comparing-matrices-mine-grun]] - A comparison of the count matrices produced by Galaxy CelSeq2 workflow, and that by MPI perl scripts, particularly with attention paid to the number of repeating elements

**** Hobbies
***** Leisure
      Cycling, Snowboarding, Wandering. Usually do all in an ill-equipped care-free fashion. I should probably add something useful here. Oh well.
***** Emacs                                                           :emacs:

      My pride and joy. Small and friendly community I love to contribute to.
****** General Packages                                               :other:
+ [[https://gist.github.com/09ef535a0a44fa49ca482e84c5e9399d][emacs config]] - My Emacs config, constantly updated, broken, updated.
+ [[https://github.com/mtekman/elisp-depmap.el][elisp-depmap.el]] - Writes out a graphviz map based on project functions
+ [[https://github.com/mtekman/remind-bindings.el][remind-bindings.el]] - Reminders for your init bindings
+ [[https://github.com/mtekman/terminal-toggle.el][terminal-toggle.el]] - Elisp package for toggling a terminal
+ [[https://github.com/mtekman/wiki-drill.el][wiki-drill.el]] - Elisp library to convert wiki-summary texts into org-drill
+ [WIP] [[https://github.com/mtekman/planemo-mode.el][planemo-mode.el]] - A mode to generate Galaxy XML tool files

****** Org-Mode Packages                                            :orgmode:     
     
+ [[https://github.com/mtekman/org-tanglesync.el][org-mode-manager]] - A tree-like management tool for your org-mode files
+ [[https://github.com/mtekman/org-treeusage.el][org-treeusage.el]] - Examine the density of org headings
+ [[https://github.com/mtekman/org-treescope.el][org-treescope.el]] - Provides a time and priority based sparse tree interaction mode
+ [[https://github.com/mtekman/org-tanglesync.el][org-tanglesync.el]] - Sync changes between internal org-mode source blocks and tangled files
+ [[https://github.com/mtekman/org-calories.el][org-calories.el]] - A calorie tracking food and fitness package for logging your intake/outtake

***** Random

****** Productivity
+ ZoteroGoogleDrive-PDFLinker - [[https://github.com/mtekman/ZoteroGoogleDrive-PDFLinker][Local]] version, and [[https://github.com/mtekman/ZoteroGoogleDrive-PDFLinker-Cloud][Cloud]] version - Unites your google drive storage with your Zotero database.
+ [[https://github.com/mtekman/ShellUtils][ShellUtils]] - Shell functions and scripts for general work (and play) use.

****** Security
+ [[https://github.com/mtekman/PAM-curses-warning-formatter][PAM-curses-warning-formatter]] - An example curses program tied in with PAM authentication that executes upon (maxtry) failure
+ [[https://github.com/mtekman/iptables-autobanner][iptables-autobanner]] - Checks journalctl logs for forced entry and adds malicious ip to the iptables ban list, run ideally with cron.

****** Games and Javascript Demos

+ [[https://github.com/mtekman/Slidey][Slidey]] - HTML5 Slides Creator and Editor
+ [[https://github.com/mtekman/diaspora_installer][diaspora-installer]] - Installer for the BattleStart Galactica Diaspora mod of the FreeSpace2 game
+ [[https://github.com/mtekman/runescape-motiondetector][runescape-motiondetector]] - Looks for mineable items in Runescape using OpenCV blob detection, and simulates mouse clicks in Xorg
+ P2 Raycast Demo - Raytracing test using Canvas and pixiJS
+ TreeDemo - Messing around with generational trees. For a much more professional outlook, see the Benchmark test in HaploForge.

****** Other
+ [[https://github.com/mtekman/PyFlogger][PyFlogger]] - CLI python food logger and calorific content displayer
+ [[https://github.com/mtekman/AlbumMaker][AlbumMaker]] - Automates anonymous album creation using a dragndrop interface with unix backend.
+ [[https://github.com/mtekman/maemo_alarm][maemo-alarm]] - Commandline tool to interface with alarmd library on maemo.

